=head1 Running LaTeXcombine in Komodo

As with all Tarp scripts, C<talatexcombine> is run in Komodo as an external
command; double clicking one of the icons in the C<LaTeXcombine> folder in the
C<Tarp Toolkit> project will run the script with certain command-line
options.  Only a few of the most common options are available through Komodo;
use the program directly from the command line for other combinations. 

In order to use this script from Komodo (with the exception of C<README>,
C<--version> and C<--help>), a C<.pklist> file must be open and visible in the
Komodo workspace.

These commands also require that you have a C<TAS> file called C<TASfile>, C<TASfile.txt>
or C<TASfile.tas> in the same directory as the C<.pklist> file.  If you need
to use another C<TAS> file, you will need to run the program using the C<--tas>
option from the command line.

=head2 Options

=for html <center><img src="images/options.png"></center>

=over

=item [current .pklist]

Displays the following dialog:

=for html <center><img src="images/screenshot1.png"></center>

This dialog will help you pick which files are to be combined (merged) by the
LaTeXcombine program using the instructions in your pickup list.

The dialog is split into the "Pickup Files" and "Preamble" sections. The "Pickup
Files" section contains one line per file in the pickup list. First, the pickup
file ID is displayed ("foo" and "bar" in this example). Then, the amount of
times each file appears in the pickup list appears, sorted in order of
occurrence. (In the dialog above, the fileID "foo" appears twice in the piciup
file, and "bar" once). A text field with the name of the pickup file follows. If
the pickup file exists, the next column, labeled "exists?" displays "yes" (or if it
doesn't, "no"). If the correct file does not appear in the text entry box, the
"Browse" button allows you to choose a different file from somewhere in your
computer.

The "Preamble" section allows you to select where the preamble of the output
.tex file will come from. If one of the names of the pickup lists is selected,
the preamble will be taken from that file. In this case, the preamble is taken
to be everything up to the first exercise. Also, at the bottom of the list the
word "new" appears. If selected, a "canned" preamble will be inserted. See
L<Tarp::LaTeXcombine> for how to change the contents of the canned preamble,
or the next section for more details about getting the preamble from a (non-new)
pickup file.

Once all of the pickup files have been specified (meaning that the "exists?" column
contains "yes" for each pickup file), the OK button can be clicked to call the
program C<talatexcombine> with the correct command-line options.

The script is run in the directory where the current file resides.
If successful, a list of chunks of continuous input will be shown in the
"Command Output" pane in Komodo.

=item README

Displays this help file.

=item --version

Equivalent to running the following in a command prompt:

    talatexcombine --version

=item --help

Equivalent to running the following in a command prompt:

    talatexcombine --help

=back

=head2 TAS Entries

=over

=item *

C<beginTag>, C<endTag>, C<exTag>, C<partTag>, C<subPartTag>, C<sequenceRestart>

The usual LaTeXtract tags

=item *

Any other tags that do not have an EXCLUDE sub entry

All other tags will be matched against the input, and when a match is found
the variable contents from the match will be stripped out and replaced with
the variable name.  Use with caution and be as specific as you can.

As an example, you could use a C<chapHead> entry to catch chapter headings:

    chapHead = \\chaphead\[$CHAP$
        chapHead::CHAP = \d\d?

=head2 Output

If your input was called foo.tex, two files will be created:

=over

=item foo.chunk

Contains "chunks" copied over from your pickup TeX files or generated using the
"new" virtual pickup file.  Chunks are delimited by CHUNK_START and CHUNK_END.

=item foo.skel

Contains a "skeleton" for a TeX file with slots to insert the preamble and
chunks in the Chunk file.  The skeleton file is generated by LaTeXcombine
using the first entries in your TAS file tags C<beginTag>, C<endTag>, C<exTag>,
C<partTag> and C<subPartTag>.  This is why the first value in these tags must be
in a printable ("canonical") format - the most common way for such a tag to be
written, without any wildcards or other weird and wonderful Regular Expression
stuff.

In other words, this is a canonical tag:

    "\\item\[\\hfill $ITM$\.\]"

because it can be printed as

    \item[\hfill $ITM$.]

but this is not a canonical tag:

    \\item\[.*?$ITM$\.\]

because, how would we print the C<.*?> bit, which means "any character"? It is
ambiguous, and not printable. Others B<not> permitted are C<\w> (word
characters), C<\d> (digits), C<\s> (spaces), unescaped stars, parentheses,
and pretty much everything else that makes a RX interesting.

=back

=head2 Getting the Preamble from a Pickup File

When using a preamble extracted from an existing file, everything up to the
first C<beginTag> of the source file is put into the first chunk in the chunk
file. If possible, the chapter and section numbers are stripped and replaced
with $CHAP$ and $SECT$, respectively; see chapHead and sectHead below.

B<IMPORTANT NOTE>:  Only one occurrence of the chapter and section numbers will be
stripped per line. This means that if the preamble of the pickup file contains this:

=for html <center><img src="images/preamble1.png"></center>

the result will be this:

=for html <center><img src="images/preamble1_res.png"></center>

which is probably not what you want, since the second "2.5" in the section heading
still shows up.  Instead, modify the input file so it looks like this:

=for html <center><img src="images/preamble2.png"></center>

which is equivalent in LaTeX terms; the chapter and section can now be stripped
correctly (given the correct values in chaptHead and sectHead, see below.)  The
output will now look like this:

=for html <center><img src="images/preamble2_res.png"></center>

